name: xeus-kernel
channels:
  - https://prefix.dev/emscripten-forge-dev
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - jinja2
  - matplotlib
  - numpy
  - pandas
  - scipy
  - plotly
  - networkx
  - simpy
